name: "Terraform workflow for Destroy"

on:
  workflow_dispatch:
    inputs:
      tfvars_filename:
        description: "Name of tfvar file"
        required: true
        type: choice
        options:
        - dev.tfvars
        - prod.tfvars
      workspace_name:
        description: "Enter the name of the workspace"
        required: true
        type: string


jobs:
  terraform:
    name: "Terraform Destroy"
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY : ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN : ${{ secrets.AWS_SESSION_TOKEN }}


    steps:
      - name: Checkout
        uses: actions/checkout@v4
    
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
      
      - name: Terraform Format
        id: fmt
        run: terraform fmt 

      - name: Terraform Init
        id: init
        run: terraform init

      - name: Terraform Workspace change
        id: workspce_change
        run: terraform workspace new ${{ inputs.workspace_name}}

      - name: Terraform Workspace
        id: workspce
        run: terraform workspace show

      - name: Terraform Plan
        id: plan
        run: terraform plan -var-file="${{ inputs.tfvars_filename}}"
      
      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve  -var-file="${{ inputs.tfvars_filename}}"
